# Generated by Django 5.1.4 on 2024-12-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voxotronform',
            name='vote_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
