# Generated by Django 5.1.4 on 2024-12-31 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_voxotronform_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voxotronform',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campusstudent'),
        ),
    ]
